# Generated by Django 2.2 on 2020-10-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decodeddata',
            name='Data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decodeddata',
            name='ImagePath',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='decodeddata',
            name='LengthOfString',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
