# Generated by Django 2.2 on 2020-10-09 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfileManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinformation',
            old_name='Image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='profileinformation',
            name='name',
        ),
        migrations.AddField(
            model_name='profileinformation',
            name='ob',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
