# Generated by Django 2.2 on 2020-10-09 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfileManagement', '0002_auto_20201009_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinformation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='profileinformation',
            name='ob',
        ),
        migrations.AddField(
            model_name='profileinformation',
            name='gender',
            field=models.CharField(max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='profileinformation',
            name='mobile_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profileinformation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
