# Generated by Django 2.2 on 2020-10-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0003_auto_20201009_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinformation',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profileinformation',
            name='mobile_no',
        ),
    ]
