# Generated by Django 2.2 on 2020-10-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0004_auto_20201010_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinformation',
            name='gender',
            field=models.CharField(max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='profileinformation',
            name='mobile_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
