# Generated by Django 2.2 on 2020-10-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0005_auto_20201010_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinformation',
            old_name='image',
            new_name='profilepic',
        ),
    ]
