# Generated by Django 2.2 on 2020-10-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0006_auto_20201010_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinformation',
            name='coverpic',
            field=models.ImageField(blank=True, null=True, upload_to='images/coverpic/'),
        ),
        migrations.AlterField(
            model_name='profileinformation',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profilepic/'),
        ),
    ]
