# Generated by Django 2.2 on 2020-10-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0007_auto_20201010_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinformation',
            old_name='mobile_no',
            new_name='nickname',
        ),
    ]
