# Generated by Django 2.2 on 2020-10-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0008_auto_20201012_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinformation',
            name='gender',
        ),
    ]
