# Generated by Django 2.2 on 2020-10-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='Image',
        ),
    ]
