# Generated by Django 2.2 on 2020-10-12 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncodedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_Name', models.CharField(max_length=20, null=True)),
                ('Starting_Index', models.IntegerField(blank=True, null=True)),
                ('Ghap', models.IntegerField(blank=True, null=True)),
                ('Add_a_Value', models.IntegerField(blank=True, null=True)),
                ('Data', models.TextField(blank=True)),
                ('DataImage', models.ImageField(blank=True, null=True, upload_to='images/data/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
