# Generated by Django 2.2 on 2020-10-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Encode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encodeddata',
            old_name='Data',
            new_name='HiddenData',
        ),
    ]
