# Generated by Django 2.2 on 2020-10-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encode', '0002_auto_20201013_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodeddata',
            name='HiddenData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
