# Generated by Django 2.2 on 2020-10-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encode', '0003_auto_20201013_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encodeddata',
            name='Image_Name',
        ),
        migrations.AddField(
            model_name='encodeddata',
            name='HiddenImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/data/'),
        ),
    ]
