# Generated by Django 2.2 on 2020-10-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encode', '0004_auto_20201015_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='encodeddata',
            name='LengthOfString',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
