# Generated by Django 2.2 on 2020-10-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Encode', '0005_encodeddata_lengthofstring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encodeddata',
            name='HiddenImage',
        ),
    ]
